[package]
name = "wicked"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
itertools = "0.12.0"
tokio = { version = "1.35.1", features = ["full"] }
tokio-postgres = "0.7.10"
